### ISSUE TITLE
the formulas MAX([1,2,3]) and MIN([1,2,3]) have incorrect result

### ISSUE THREAD

**Issue by Sluchik** [handsontable/formula-parser#100]
![image](https://user-images.githubusercontent.com/13663547/73389526-02c6a580-42dd-11ea-95fb-e3f066c24c99.png)

**Comment by AMBudnik** [comment]
Hey @Sluchik 

that's a syntax error. Just skip the array and pass values like that `parser.parse('MAX(77,2,35)'); `

**Comment by Sluchik** [comment]
Hay @AMBudnik ,
Thank you for the response. Yes, it works when we skip array.  But I think it is a backward compatibility issue, as in versions 3.0.0  formulas as MIN MAX AVERAGE  were working with array too

![image](https://user-images.githubusercontent.com/13663547/73435624-afdb0580-4351-11ea-9220-5934a94702ec.png)

**Comment by AMBudnik** [comment]
I might say that it was an unexpected design pattern before. I'm not able to test it on Excel but Google Sheets does not use arrays. If we want to keep consistency between formula-parser and tools that people use to handle formulas (Google Sheets, Excel) we need to keep the same syntax.

**Comment by Sluchik** [comment]
As I see SUM formula works in both ways in new version.
![image](https://user-images.githubusercontent.com/13663547/73437269-b61eb100-4354-11ea-853f-73ebe6c3661b.png)

Also according to Google sheet, that supports two types of input parameters 
1. Like the range of parameters. Also, formula parser has a hook for a range  of values "callRangeValue'" 
![image](https://user-images.githubusercontent.com/13663547/73437423-f8e08900-4354-11ea-8155-5aa14e1bb193.png)
2. And separate input. For them we use callCellValue'
![image](https://user-images.githubusercontent.com/13663547/73437743-950a9000-4355-11ea-8656-b237cae51dfc.png)

**Comment by Sluchik** [comment]
But anyway thank you for the response parser.parse('MAX(77,2,35)') will be suitable for me
