### ISSUE TITLE
DATEVALUE("1/1/1900") formula has a different result with Google Sheet

### ISSUE THREAD

**Issue by Sluchik** [handsontable/formula-parser#101]
DATEVALUE("1/1/1900")  

formula parser - result:1
![image](https://user-images.githubusercontent.com/13663547/73542743-13daf800-443e-11ea-88b1-558b8f9eb8f8.png)

google sheet   - result:2

![image](https://user-images.githubusercontent.com/13663547/73542804-3240f380-443e-11ea-8fb1-a62eb94f804b.png)

**Comment by AMBudnik** [comment]
Maybe I'm being too brave here accusing Google but in the official Excel support page it is said that

> Excel stores dates as sequential serial numbers so that they can be used in calculations. By default, January 1, 1900 is serial number 1

src https://support.office.com/en-us/article/datevalue-function-df8b07d4-7761-4a93-bc33-b7471bbff252

so the value should be `1`, not `2`.

I don't have an ability to check this on Excel for Windows but in Excel for Mac v`16.16.11` we get `1`.
