### ISSUE TITLE
Non alphabet characters in variable handsontable variable names returning REF# or #ERROR!

### ISSUE THREAD

**Issue by appsworld** [handsontable/formula-parser#114]
Using non-alphabet characters in handsontable variable names results in a reference error.

E.g
https://jsfiddle.net/jcsfgq2d/5/

**Comment by AMBudnik** [comment]
Hi @appsworld 

the following issue seems to be already reported here https://github.com/handsontable/formula-parser/issues/109
If you feel that https://github.com/handsontable/formula-parser/issues/109 lacks some information please feel free to add your comment.
