### ISSUE TITLE
SUM of 2 Cells Not Working? 

### ISSUE THREAD

**Issue by JohnTendik** [handsontable/formula-parser#21]
https://jsfiddle.net/40x85sxq/5/

parser.on('callCellValue', function(cellCoord, done) {
  console.log(data[cellCoord.row.index][cellCoord.column.index]);
});

var resultObj = parser.parse('SUM(A1,B2)');

`resultObj.result output as 0, no error`

The values are working, I can see the console.log output of the cell values, which is 10 and 11, but the sum doesn't work, only outputs 0.

Is there something I'm doing wrong? If so I apologize, If not I thought I should mention it here.

**Comment by budnix** [comment]
Hi @JohnTendik, I've looked into your demo and found that you forgot to add callback call inside `callCellValue` hook. After applying this patch it works (https://jsfiddle.net/40x85sxq/6/). Can you confirm?

**Comment by JohnTendik** [comment]
Oh Boy,

That seemed to have worked, Jeez it was my fault all along :D 

Thank you for the quick reply mate! Sorry for the issue clutter

John
