### ISSUE TITLE
question: how to use `formula-parser` with `handsontable-ruleJS`

### ISSUE THREAD

**Issue by JerryYangJin** [handsontable/formula-parser#26]
Is there any example on how to use `formular-parser`?
I played with [handsontable-ruleJS](https://github.com/handsontable/handsontable-ruleJS/), the finance formulas are not in `SUPPORTED_FORUMLAS`, simplay add `NPV`, `PMT` etc to `SUPPORTED_FORUMLAS` doesn't work, they always return `NaN`
I can see the `SUPPORTED_FORUMLAS` in this project already includes finance formulas, how to use it with `handsontable`? thanks!

**Comment by JerryYangJin** [comment]
with some modification from [handsontable-ruleJS](https://github.com/handsontable/handsontable-ruleJS/), it can work with `formular-parser`

**Comment by prakashbist** [comment]
@JerryYangJin  will you please tell what modification is required ?
