### ISSUE TITLE
Support for EXP

### ISSUE THREAD

**Issue by swistach** [handsontable/formula-parser#27]
Support for EXP():
- [x] '#N/A' when has been called without `argument`
- [x] '#NAME?' when argument is out of known range
- [x] '#ERROR!" for non numeric argument
- [x] '#ERROR!" when has been called with more than one argument
- [x] tests

**Comment by rbarato** [comment]
Any ETA on when this will be available in the nest handsontable release?

Thanks

**Comment by AMBudnik** [comment]
Hi @rbarato if the solution will pass the final tests it looks like it will get published.
Hi @swistach is it a part of v1.12.1 ?

**Comment by rbarato** [comment]
Hi @AMBudnik, thanks for the reply!

**Comment by swistach** [comment]
EXP support should be available in Handsontable v1.12.1
