### ISSUE TITLE
Formula with cell reference not working

### ISSUE THREAD

**Issue by navindharmaraj** [handsontable/formula-parser#33]
Hi,
Am trying to calculate a formula like C1+2 by using the method parser.parse('C2+2') , I end up getting error like {error: "#VALUE!", result: null}.

**Comment by budnix** [comment]
Hi @navindharmaraj, `formula-parser` doesn't know anything about `'C2'` cell coordinate. To make this work you have to provide values according to passed coordinates. You have to put your login into `'callCellValue'` hook and `'callRangeValue '` hook if you want to use cell ranges (see https://github.com/handsontable/formula-parser#api-hooks). 

I've prepared a simpelfied demo at https://www.webpackbin.com/bins/-L-fB_9UeY-wznvC2Fak.

**Comment by navindharmaraj** [comment]
Hi @budnix, Thanks for your quick reply.
 The example is working fine. Currently am stuck if my data source is a nested array(nested rows and headers).

**Comment by MedinaGitHub** [comment]
link fail https://www.webpackbin.com/bins/-L-fB_9UeY-wznvC2Fak .

**Comment by h8art** [comment]
Link is broken. If it possible to add it as an example, because its very useful for those who make their own formulas, thanks

**Comment by budnix** [comment]
Hi, I've recreated a similar demo on fiddle. An example for `callCellValue` hook https://jsfiddle.net/budnix/2nmjh0t4/ and https://jsfiddle.net/budnix/pLsct5yo/ for `callRangeValue` hook.
