### ISSUE TITLE
Dependency on github repo (formula.js)

### ISSUE THREAD

**Issue by AWulkan** [handsontable/formula-parser#34]
We're having slight problems with using Handsontable due to a dependency in this repo. It seems like [formula.js](https://github.com/handsontable/formula.js) is being cloned from a github repo instead of just from npm.

The problem we have is that our build server is pretty locked down behind a firewall and won't allow access to Github. Setting up exceptions in the firewall would work, but it's not an ideal solution,

I know that this is a rare problem to have, but is there any chance that formula.js could be moved to npm?

Thanks.

**Comment by AMBudnik** [comment]
The behavior has been changed in the latest version of the library
