### ISSUE TITLE
Modulus (%) doesn't work

### ISSUE THREAD

**Issue by cole21771** [handsontable/formula-parser#35]
**Steps to reproduce:**
1. Put the code below in a file named `test.js`
`const FormulaParser = require('hot-formula-parser').Parser;`
`let parser = new FormulaParser();`
`console.log(parser.parse("10 % 3"));`

2. Run `npm install hot-formula-parser`

3. Run the program with `node test.js`

4. See it output `{ error: '#ERROR!', result: null }`

This should work. It should return `{ error: null, result: 1 }`

**Comment by AMBudnik** [comment]
Confirmed, we're getting `{error: "#ERROR!", result: null}` once we want to count any modulo.

**Comment by wojciechczerniak** [comment]
There is no modulo in formulas. `%` character is reserved for „percentage” operator. To calculate modulo you need to use a function.

**Comment by AMBudnik** [comment]
> To calculate modulo you need to use a function.

Good enough. We can close this topic.
