### ISSUE TITLE
How to deal with floating point number precision in JavaScript?

### ISSUE THREAD

**Issue by qiumobai** [handsontable/formula-parser#38]
I have the formula：
a=0.1,b=0.2; sum(a,b);
This will print the result 0.30000000000000004

**Comment by AmBeta** [comment]
I met this problem too. It's a common issue in javascript when calculating.

Is it possible to provide API hooks for rewriting the action of '+', '-', '/' etc.
Thus we could use some other libraries like big.js to hook in the calculation.

**Comment by kreja** [comment]
> I met this problem too. It's a common issue in javascript when calculating.
> 
> Is it possible to provide API hooks for rewriting the action of '+', '-', '/' etc.
> Thus we could use some other libraries like big.js to hook in the calculation.

Sounds like a good idea, but it seems that this project is no longer maintained, see https://github.com/handsontable/formula-parser/issues/68#issuecomment-485768557

Have you solved this problem by any fork or other ways?

**Comment by AMBudnik** [comment]
We encourage everyone to create forks. It'll be great if someone would benefit from this fork and move on with the development. As @kreja spotted we're working on a new formula engine so we won't need this fork in the future.

**Comment by AMBudnik** [comment]
I'm closing this issue as it doesn't relate to a bug in the project. However, you are still welcome to fork the repository or leave feedback for other users.

**Comment by l33tllama** [comment]
I have had this issue with the Joplin Markdown Calc plugin that uses this library https://github.com/oswida/joplin-markdown-calc 
I found a potential solution if anyone is interested in solving it :) https://www.thewebflash.com/solution-for-floating-point-problems-in-javascript/
