### ISSUE TITLE
Math constants containing numbers like `LN10()` return an error

### ISSUE THREAD

**Issue by tzimmermann** [handsontable/formula-parser#39]
[According to the feature list](https://github.com/handsontable/formula-parser#features), functions like `LN10()` should return the appropriate constant value.
However, when I do this:

```
var hotFormulaParser = require("hot-formula-parser")
var parser = new hotFormulaParser.Parser();

parser.parse('LN10()')
```
I get
```
{ error: "#NAME?", result: null }
```

It only seems to happen with constants that contain a numeric value, `PI()` and `E()` are working, so maybe it's related to [this parsing issue](https://github.com/handsontable/formula-parser/issues/29#issuecomment-342011978).

**Comment by AMBudnik** [comment]
Thank you for your suggestion @tzimmermann 

we have currently held the development of this project. The formula-parser was made to support our Formula plugin for Handsontable library but we will be checking this plugin later this year,

**Comment by AMBudnik** [comment]
It may be related to the same subject as here https://github.com/handsontable/formula-parser/issues/40

**Comment by AMBudnik** [comment]
That's true. This is the same topic as https://github.com/handsontable/formula-parser/issues/29 and https://github.com/handsontable/formula-parser/issues/40
