### ISSUE TITLE
Varible names issue

### ISSUE THREAD

**Issue by AndreyBespamyatnov** [handsontable/formula-parser#40]
I tried to setup custom variables, It looks like if I’m using the name with numbers it is doesn’t work, but without numbers, it works perfectly.

![screenshot_3](https://user-images.githubusercontent.com/2779266/36992577-689959ba-20bc-11e8-8bfe-e86c7b12d5c4.png)

**Comment by AMBudnik** [comment]
I have replicated the issue but did not find any workaround. For the first glance, it looks like a bug with a regex. But I do not know if the project that we forked has this issue solved.

**Comment by adoura** [comment]
i think issue root cause is the conflict between RELATIVE_CELL regex and VARIABLE regex. i didn't figure yet how to solve it.

**Comment by afaraha8403** [comment]
Hello @AndreyBespamyatnov and @AMBudnik 

did you guys manage to find a solution for this?  Currently can't use variables in anything

**Comment by AMBudnik** [comment]
Hey @afaraha8403 
we're working on a new formula engine so I guess that we won't make any changes for this repository. After we finish the project it can become redundant.

**Comment by AMBudnik** [comment]
The same as https://github.com/handsontable/formula-parser/issues/29
