### ISSUE TITLE
BUG: ISBLANK() always results in false

### ISSUE THREAD

**Issue by tarunvelli** [handsontable/formula-parser#42]
The ISBLANK() function seems to have a bug because the result is always false or errors out.
formula-parser version 2.3.3, tested using node v6.3.1 (npm v3.10.5) and using node v8.9.4 (npm v5.6.0)

> parser.parse('ISBLANK()')
{ error: null, result: false }
> parser.parse('ISBLANK("")')
{ error: null, result: false }
> parser.parse('ISBLANK(null)')
{ error: '#NAME?', result: null }
> var x = null
undefined
> parser.parse('ISBLANK(x)')
{ error: '#NAME?', result: null }

Is this a known issue? or am I using it wrong?

**Comment by tarunvelli** [comment]
Oh, didn't know that, thanks for pointing it out.
So behaviour wise, is it wrong to expect parser.parse('ISBLANK()') also to
result true?

**Comment by budnix** [comment]
If the built-in functions don’t fill your requirements you can overwirite their logic, like this
```
parser.setFunction('ISBLANK', function(v) {
    return v == null || v === '';
});
```

**Comment by tarunvelli** [comment]
Thanks again! closing this issue as its answered.
