### ISSUE TITLE
How to pass formula parser into handsontable instance?

### ISSUE THREAD

**Issue by nosir** [handsontable/formula-parser#44]
Hello there,

I had looked every where but am still confused how to pass a parser into hot instance.
There is an option to pass `formulas={variables:{...}}` in hot doc but that's the only thing.

I know there must be a way to do that but it's kinda vague and not mentioned anywhere in the doc.

Thanks

**Comment by shiyuanzheng** [comment]
Hi,Is your problem solved? I also encountered the same problem, I don't know how to deal with it, can you tell me your solution? thank you very much.

**Comment by AMBudnik** [comment]
Hey @shiyuanzheng 

Handsontable has a [plugin called Formula Support](https://handsontable.com/docs/7.0.0/demo-formula-support.html), which work on the parser logic.

**Comment by shiyuanzheng** [comment]
Hey @AMBudnik 
Sorry, I noticed that the Formula Support plugin is a feature that the Pro version can use. Because this is a personal non-commercial project, I may not be able to use the Pocket Edition Pro, so I want to build support for formula functions based on handsontable.js.

**Comment by wojciechczerniak** [comment]
Then you have to create your own formula plugin for Handsontable and implement everything from scratch. There's no way to "just" pass formula parser into Handsontable. It has to handle data modification, findex mappings (for sort, filters etc), circular dependencies, recalculate formulas and so on. Quite a task ahead of you.
