### ISSUE TITLE
setFunction() not working

### ISSUE THREAD

**Issue by monica18p** [handsontable/formula-parser#48]
**Parser.ts**
```
this.parser.setFunction('VLOOKUP', function (params) {
            let searchKey = params[0]
            var range = params[1]
            let index = params[2]
            range = this.parser.getVariable(range) // Should be of type Array<tuple>
            var valueFromRange = 0
            if (range instanceof Array) {
                let matchedTuple = range.find(function (element) {
                    if (element instanceof Array && element.length > 0) {
                        if (element[0] == searchKey) {
                            return true
                        }
                    }
                    else {
                        return true
                    }
                })

                if (matchedTuple) {
                    valueFromRange = matchedTuple[index]
                }
            }
            return valueFromRange
        });
```

**HomePage.ts**
```
FormulaParser = require('hot-formula-parser').Parser
this.parser = new this.FormulaParser()
let TEMPRANGE = [
      [1, 'apple', 'banana', 3, 4], 
      [2, 'oi', 'stawberry', 'cik', 44], 
      [3, 55, 66, 77, 88]
    ]
this.parser.setVariable('TEMPRANGE', TEMPRANGE)
let parsed = this.parser.parse(exp);
console.log('Parsing ' + exp)
console.log(parsed)
```

output:-

> Parsing VLOOKUP(1,TEMPRANGE,2)
> {error: "#NAME?", result: null}

Please mention if I am missing something. I have followed as mentioned in documentation.

Thanks.

**Comment by budnix** [comment]
I think that you unnecessary tried to parse `TEMPRANGE` variable where it is already parsed in the `VLOOKUP` function. I've created fixed demo based on your code https://jsfiddle.net/txeLdfu7/.

**Comment by monica18p** [comment]
I tried with your code but didn't work :(
Following is my ionic info

`$ ionic info`

> cli packages: (/usr/local/lib/node_modules)
> 
>     @ionic/cli-utils  : 1.19.2
>     ionic (Ionic CLI) : 3.20.0
> 
> global packages:
> 
>     cordova (Cordova CLI) : 8.0.0
> 
> local packages:
> 
>     @ionic/app-scripts : 3.1.9
>     Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.4
>     Ionic Framework    : ionic-angular 3.9.2
> 
> System:
> 
>     ios-deploy : 1.9.2
>     Node       : v8.11.1
>     npm        : 6.1.0
>     OS         : macOS High Sierra
>     Xcode      : Xcode 9.1 Build version 9B55
> 
> Environment Variables:
> 
>     ANDROID_HOME : not set
> 
> Misc:
> 
>     backend : pro

**Comment by budnix** [comment]
I assume that jsfiddle demo works but now there is a problem with the ionic environment? Maybe there are some compilation or runtime errors or logs that can help to understand the problem?

**Comment by monica18p** [comment]
So sorry... It was my mistake. I didn't copy paste your code properly into mine. 
Your code worked. You were right, there is no need of getting the variable again.

Thanks a lot!!

Closing the issue 👍
