### ISSUE TITLE
Issue with conditional/complex formulas

### ISSUE THREAD

**Issue by monica18p** [handsontable/formula-parser#49]
I am trying to parse a conditional formula like below

`ROUND(10*IF(10<=20,20.2222,40.22222),2)`

But i get following output

> {"error":"#ERROR!","result":null}

or 

`(ROUND(10*IF(10<=20,20.222,40.222)*100,2)+10*100*(1=1)+ROUND(100*2,2))*(1<=50)`

> {"error":"#NAME?","result":null}

I have checked the brackets also. I have a sheet having formulas, its working in spreadsheet but doesn't work when I parse.
Am I missing something or conditional formulas don't work for now?

Thanks.

**Comment by budnix** [comment]
I've checked the formulas that you provided and first one seems parsed correctly https://jsfiddle.net/uxbw69L0/3/. The second formula is a little tricky because it makes some basic math calculation based on the number and `true/false` values which in this case are treated as `#VALUE!` error. If you remove that `true` values (`(1<=50)` and `(1=1)`) from the formula expression it calculates correctly.

**Comment by monica18p** [comment]
Is there a way where I can set flag to replace `true = 1` & `false = 0`?
Because thats what spreadsheet does. In this way the parsing won't break

**Comment by monica18p** [comment]
I tried to set the variable for true and false
```
this.parser.setVariable('true', 1)
this.parser.setVariable('TRUE', 1)    
this.parser.setVariable('false', 0)
this.parser.setVariable('FALSE', 0)
```

`this.parser.parse('true')`

> {"error":null, "result":1}

`this.parser.parse('false')`

> {"error":null, "result":0}

But while parsing 
`(ROUND(10*IF(10<=20,20.222,40.222)*100,2)+10*100*(1=1)+ROUND(100*2,2))*(1<=50)`

> {"error":"#VALUE!","result":null}

I get same error as before.

**Comment by budnix** [comment]
You can overwrite `true/false` values to numbers using this *workaround* https://jsfiddle.net/9h6kjrwc/7/. Keep in mind that this change may break the calculations for another formula expressions.

**Comment by monica18p** [comment]
For now I have changed the expression from
`(ROUND(10*IF(10<=20,20.222,40.222)*100,2)+10*100*(1=1)+ROUND(100*2,2))*(1<=50)`
to
`(ROUND(10*IF(10<=20,20.222,40.222)*100,2)+10*100*(IF(1=1,1,0))+ROUND(100*2,2))*(IF(1<=50,1,0))`

Wherever `true/false` may occur I have replaced it with `IF(condition,then,else)`
With this I get correct output. But it would be great if the parser could do this internally. Hope you guys could roll out this feature soon.

Thanks. Parser is really helpful!

**Comment by monica18p** [comment]
I have encountered another issue regarding conditional expression.
In spreadsheet the expression is :
`IF((20<61)*(20>=18),"Eligible","Not Eligible")`

Parser output:

> {error: "#VALUE!", result: null}

**Alternative**: Replace `*` with `=`
`IF((20<61)=(20>=18),"Eligible","Not Eligible")`

Parser output:

> {error: null, result: "Eligible"}

Thought to comment in same issue, instead of creating another issue.
If my interpretation is correct then I would suggest to add this in your documentation.

Thanks.
