### ISSUE TITLE
Some Percentage equations are off

### ISSUE THREAD

**Issue by stoplion** [handsontable/formula-parser#53]
parser.parse('100 - 10%')
//result: 99.9
parser.parse('100 + 10%');
result: 100.1

etc..

**Comment by AMBudnik** [comment]
It works the same in Google Sheets.

If you'd like to add `10%` of `100` it's more

`parse('100+(100*10%)')`.

In this case, `10%` is the same same `1/10` or `0.1` so it gives correct results.
