### ISSUE TITLE
MONTH, YEAR, DAY functions give wrong output

### ISSUE THREAD

**Issue by monica18p** [handsontable/formula-parser#54]
These functions are not working correctly. Please take a look at following outputs
`MONTH(1/2/1977)`

> {error: null, result: 12}

`YEAR(2/1/1977)`

> {error: null, result: 1899}

`DAY(2/1/1977)`

> {error: null, result: 31}

`MONTH(7/26/2018)-MONTH(2/1/1977)`

> {error: null, result: 0}

Please let me know if there is any mistake in the syntax.

**Comment by leonelcamara** [comment]
MINUTE also seems to always return 23 for me

**Comment by AMBudnik** [comment]
For
`MONTH(1/2/1977)`
`12` is what we also get in Google Sheets. The same results we get if we type `YEAR(2/1/1977)` (we get `1899`). And the `MONTH(7/26/2018)-MONTH(2/1/1977)` is also `0` in the Sheets.

There's one difference though. For
`DAY(2/1/1977)`
Google Sheets returns `30`, not `31`.

It looks like the `/` char is not the one to use in the syntax https://www.ablebits.com/office-addins-blog/2015/04/22/excel-month-eomonth-functions/

**Example**: If we use `"15-Apr-2015"` for `MONTH` it shows us `4` as expected.

Not sure what's going on here

> There's one difference though. For
> `DAY(2/1/1977)`
> Google Sheets returns `30`, not `31`.

but I guess that we can close this subject.
