### ISSUE TITLE
Issues with IF fomula

### ISSUE THREAD

**Issue by meodemsao** [handsontable/formula-parser#55]
When i use IF(TRUE, 1, 2) or IF(FALSE, 1, 2) running or
But when i use with coordinates IF( A1 > 0, 1, 2) alway return 2 (false)

**Comment by wuganzhi** [comment]
> 当我使用IF（TRUE，1,2）或IF（FALSE，1,2）运行时或者
> 当我使用坐标IF（A1> 0,1,2）时总是返回2（假）

How do you use the IF function, I also want to use it

**Comment by meodemsao** [comment]
@wuganzhi i use another solution, you can try this http://www.smartxls.com/ 
i think currently can't find any nodejs lib can do well

**Comment by wuganzhi** [comment]
> @wuganzhi我用另一个解决方案，你可以试试这个http://www.smartxls.com/
> 我觉得目前找不到任何nodejs lib都可以做得好

I need to edit the file on the web side, there will be a lot of computing needs, this does not meet the needs, thank you for your help!

**Comment by meodemsao** [comment]
I see
