### ISSUE TITLE
Dividing negative number by 0 returns result "true"

### ISSUE THREAD

**Issue by rf48149** [handsontable/formula-parser#57]
When I divide a negative number by zero after setting up variables, the result is "true", which is not the expected result. Could you please provide a solution for the problem and/or fix it?

Example:
  parser.setVariable('a', 0);
  parser.setVariable('b', -10);

  parser.parse('IF(a<>0;(b/a))') returns {error: null, result: true}

**Comment by AMBudnik** [comment]
Thank you for sharing the example. I have replicated the issue.

**Comment by deepakdhull012** [comment]
I think this issue is fixed now.
