### ISSUE TITLE
Is it possible to get the arguments of a formula?

### ISSUE THREAD

**Issue by velchev** [handsontable/formula-parser#61]
I have a formula to calculate, but need to get the arguments before the calculations so I can set them as a variables  in the library
so something like '(argument+arg2)*argumen' will be my formula
how to get the arguments - everything but the operators? I need to do that as value of the arguments is changing while the user interacts with the ui. I could potentially set them every time the user changes but prefer to keep them outside and only when I need the calculation to set them and calculate  the value. 
I could probably do regular expression parsing for this but was wondering if that is covered already in the library.

**Comment by AMBudnik** [comment]
Welcome @velchev 

I've just received a demo from our developer https://jsfiddle.net/budnix/xvpsd5za/1/
Hope it helps.

He adds that
> this is more a workaround than the use of API. Only the arguments for the raw expressions are logged (+,-, etc)
