### ISSUE TITLE
HLOOKUP returns #ERROR! always.

### ISSUE THREAD

**Issue by Nelladel** [handsontable/formula-parser#64]
Hi,

I'm attempting to use just the `hot-formula-parser` package to parse some Excel-like formulas, but I'm constantly getting an error on the following formula: 

`HLOOKUP(1, [[1],[2]], 2)`

As per your unit tests, this should yield `2`, but it doesn't (see: [Formula.js - Test - Lookup Reference (L50). ](https://github.com/handsontable/formula.js/blob/develop/test/lookup-reference.js#L50))

Any chance you could help me out? I've reproduced the error in [this stackblitz.](https://stackblitz.com/edit/js-96vnyu)

Thank you very much!

**Comment by AMBudnik** [comment]
like mentioned here https://forum.handsontable.com/t/hlookup-returns-error-always/3078 the formula-parser does not support the `HLOOKUP`.
Here https://github.com/handsontable/formula-parser/blob/develop/src/supported-formulas.js is a list of supported formulas.

Related topic https://github.com/handsontable/formula-parser/issues/11
