### ISSUE TITLE
Variables cannot be references inside a list/range definition

### ISSUE THREAD

**Issue by ThomasPinna** [handsontable/formula-parser#66]
You cannot use variables in list definitions.

I tried

```
parser.setVariable(a, 'pass');
parser.setVariable(b, 'pass');
parser.setVariable(c, 'fail');

console.log(this.parser.parse("COUNTIF( [ a, b, c ], 'fail' ))"
```

I expected the `COUNTIF()` to return `1`, which I expect since that is what it returns of I manually fill in the variables.

I observed a generic `#ERROR` message as soon as the list contains a variable. I observed the same behaviour for other functions that accept list/ranges.

**Comment by AMBudnik** [comment]
Hey @ThomasPinna 

a variable does not correspond to any physical address of a cell so it cannot be used as a range.

**Comment by ThomasPinna** [comment]
Hey @AMBudnik 

Thank you for your answer, I looked up a little bit on how ranges work, and I think I have found a workaround that would allow me to use variables in "ranges".

```
this.parser.on('callFunction', function (name, params, done) {
    if (name === 'LIST') {
        done(params);
    }
});
```

After this you can do:

```
this.parser.parse("COUNTIF( LIST( a, b, c ), 'fail' )");
```

I think I need to look up the exact meaning of `[...]` in the formula-parser
