### ISSUE TITLE
how to write string in double qoutes

### ISSUE THREAD

**Issue by aubrijesh** [handsontable/formula-parser#69]
Hi,
How to write string in double quotes like "Hello world"
For this I can use double double quotes in excel 
eg " ""Hello world""  " will result in "Hello world"

**Comment by AMBudnik** [comment]
Hey @aubrijesh 

you should use single quotes to wrap the double-quoted string.

Example https://jsfiddle.net/AMBudnik/0o235x49/1/

**Comment by AMBudnik** [comment]
To be honest I'm not an expert (we just forked the project to use it in Handsontable) but.. this

`parser.parse('\'\"world\"\'').result`

seem to work fine.

**Comment by aubrijesh** [comment]
thanks @AMBudnik .. I will check it ..
