### ISSUE TITLE
Async callRangeValue function

### ISSUE THREAD

**Issue by dod91** [handsontable/formula-parser#71]
Hi,
I'm pretty new to this library but is it possibile to write async function in the `callRangeValue` hook?

Something like this doesn't seem to work correctly:
```
parser.on('callRangeValue', function (startCellCoord, endCellCoord, done) {
   setTimeout(()=>{
      done([1,2,3]);
   }, 1000)
});
```

while: 
```
parser.on('callRangeValue', function (startCellCoord, endCellCoord, done) {
   done([1,2,3]);
});
```
works as expected.
Is this the expected behaviour or am I missing something?

Thanks for your help.

**Comment by AMBudnik** [comment]
Hi @dod91 

the callback cannot be async.

**Comment by dod91** [comment]
Understood, thank you for your response.
It's a pity that the `callRangeValue` function isn't async.
