### ISSUE TITLE
can not pass array as second argument of function

### ISSUE THREAD

**Issue by aubrijesh** [handsontable/formula-parser#74]
I am unable to call function who accepts first parameter as number and second parameter as array.
eg: 
var fmParser = new formulaParser.Parser()
fmParser.setFunction("VALUEATINDEX", (args) => {
        var index =  values[0];
        var array  =  values[1];
        var response = array[index - 1];
        return response;
});

fmParser.parse("VALUEATINDEX(1, [1,2,34])")

it is throwing me error
error: "#ERROR!"
result: null

**Comment by AMBudnik** [comment]
Hey @aubrijesh 

this topic has been already mentioned here https://github.com/handsontable/formula-parser/issues/7
