### ISSUE TITLE
ROW() not working

### ISSUE THREAD

**Issue by elaine1234** [handsontable/formula-parser#78]
I tried this funtion like this:
``` js
import { Parser } from 'hot-formula-parser';
const parser = new Parser();
parser.parse('ROW(A1)')
```
Instead of `{ result: 1 }`, I got `{error: "#N/A", result: null}` . What seems to be the problem?

**Comment by AMBudnik** [comment]
Hey @elaine1234 

please take a look at this topic https://github.com/handsontable/formula-parser/issues/79
