### ISSUE TITLE
How to import and use in typescript?

### ISSUE THREAD

**Issue by hamed-mahdizadeh** [handsontable/formula-parser#89]
I've tried to import js to typescript and use it but I couldn't.

import "./formula-parser.js";

import   formulaParser from "./formula-parser"

and I've added this to typings.d.ts: declare var formulaParser;

Can you explain the proper way to use your library in typescript?

**Comment by AMBudnik** [comment]
Hi @hamed-mahdizadeh 

this is a side project that was made to support formula calculations in our main project - Handsontable. It will be replaced with a new engine within 2 months. We did not prepare typings for it as we have a separate file for Handsontable.

What I can do is just share an article that may help https://www.thepolyglotdeveloper.com/2017/03/javascript-libraries-in-a-typescript-application-revisited/

**Comment by hamed-mahdizadeh** [comment]
Hi @AMBudnik 

Thanks for your response and for your help.

**Comment by AMBudnik** [comment]
Hi @hamed-mahdizadeh I highly recommend checking our new formula engine out. It was released yesterday https://github.com/handsontable/hyperformula
It lacks some formulas, but it should definitely meet all performance expectations.

**Comment by hamed-mahdizadeh** [comment]
Hi Alexandra

Thank you very much for your consideration and informing me about your new
formula engine.

Best regards,
