### ISSUE TITLE
Support for custom functions

### ISSUE THREAD

**Issue by budnix** [handsontable/formula-parser#9]
Support for custom functions. Similar to custom [variables](https://github.com/handsontable/formula-parser#setvariablename-value).

**Comment by ibrahimyilmaz7** [comment]
I really need this +1

**Comment by jeffijoe** [comment]
This would be so awesome.

**Comment by agarbund** [comment]
I created PR for this: #28

**Comment by budnix** [comment]
Thanks, @agarbund! I've merged your PR into `develop` branch and I've made a new release based on your changes (https://github.com/handsontable/formula-parser/releases/tag/2.3.0).
