### ISSUE TITLE
Custom function with Date as parameter

### ISSUE THREAD

**Issue by venquet** [handsontable/formula-parser#92]
Hi, 
We have created a custom function called DATEDIF which takes two dates as arguments to find the difference. Unfortunately, this is not working. Please find the below code snippet.  

```
var FormulaParser = require('hot-formula-parser').Parser;


function test()
{
    var parser = new FormulaParser();   
    parser.setVariable('eta', '2019-12-24');
    parser.setVariable('etd', '2019-12-26'); 

    parser.setFunction('DATEDIF', function(params) {
         
        console.log(params[0], params[1]);
        //
        parser.setVariable('DATEDIFF1', params[0]);
        parser.setVariable('DATEDIFF2', params[1]);
        //
        var date1v = parser.parse('DATEVALUE(DATEDIFF1)');
        var date2v = parser.parse('DATEVALUE(DATEDIFF2)');
        //
        return (date2v - date1v);
      });
   
    rturn = parser.parse('DATEDIF(eta, etd)');
    console.log(rturn);
    
}
test();
```
Getting output as `{ error: null, result: NaN }`

Please shed some light on this issue, we have tried other params like arrays and used SUM, AVERAGE functions inside the custom function it works perfectly. Only with date object facing this issue.

Thanks.

**Comment by AMBudnik** [comment]
I am sorry but we offer code review only for Handsontable Extended Support Clients. If you have this plan please share the license ID to support@handsontable.com

**Comment by AMBudnik** [comment]
The same issue is reported here https://github.com/handsontable/formula-parser/issues/98

If we change the variable names to contain only letters it works well.
