### ISSUE TITLE
if(1>1, 0/0, 1) evaluates "#VALUE!" 

### ISSUE THREAD

**Issue by growthzilla** [handsontable/formula-parser#97]
when using if function like this:
`if(condition, truthy value, falsy value)` evaluates truthy value even when the condition is false. The truthy evaluation may be invalid (eg. `#VALUE!`) which ends up making the result `#VALUE!`. 
For example, when computing a ratio A1/B1, if B1 is zero, it results in `#VALUE!`. To avoid that, I would like to use `if()` function to only calculate the ratio when B1 is non-zero. However, `if(B1>0, A1/B1, 0)` stil evaluates to `#VALUE!`.

**Comment by marlonkjoseph** [comment]
Microsoft Excel evaluates the expression `if(1>1, 0/0, 1)`to `1`.
I would like this behavior to be added so that I can add null checks into my formulas.

**Comment by AMBudnik** [comment]
The topic is related to diving by zero topic https://github.com/handsontable/formula-parser/issues/36

`if(1>1, 0/0, 1)` it should return `1` as `false`, however, as there's diving by zero operation in the IF statement it is returned as an error for the whole equation.
