### ISSUE TITLE
Any string followed by a number is problematic

### ISSUE THREAD

**Issue by dgrcode** [handsontable/formula-parser#98]
Any string followed by a number, such as `foo3` or `bar42` on its own will return true, but will evaluate to false in a conditional

**Comment by dgrcode** [comment]
just discovered two new things.

 * Strings like `foo_bar4` are actually processed properly
 * Strings like `foo4_bar` result in `#ERROR`

**Comment by AMBudnik** [comment]
Thank you for doing the investigation on this issue. 

We are working on a new formula engine so I am not sure if we will fix any issues on this repository. If you would like to fix anything I highly encourage you to fork it.

**Comment by dgrcode** [comment]
Hi @AMBudnik, thanks for your reply. Is there any timeline for that new formula engine to be released? Will it be open sourced?

Thanks!

**Comment by AMBudnik** [comment]
The general plan is to share the project under GPL v3 license. We're planning to publish it in Q1/2020 but we're in the 1 stage of testing and a lot of things do not work yet.

**Comment by AMBudnik** [comment]
It looks like this is the same topic as this one https://github.com/handsontable/formula-parser/issues/40

**Comment by AMBudnik** [comment]
Hi @dgrcode I highly recommend checking our new formula engine out. It was released yesterday https://github.com/handsontable/hyperformula
It lacks some formulas, but it should definitely meet all performance expectations.

**Comment by dgrcode** [comment]
awesome! Thanks for reaching out 🙌
