### ISSUE TITLE
variables not working, returns #VALUE! error

### ISSUE THREAD

**Issue by julniter** [handsontable/formula-parser#99]
I created a new instance of the parser then tried this.

![image](https://user-images.githubusercontent.com/40856322/73320851-ac754a80-427b-11ea-962d-bdb38ee79373.png)

But I kept getting #VALUE error whenever I use variables inside the expressions.

![image](https://user-images.githubusercontent.com/40856322/73320886-c2830b00-427b-11ea-97ea-f8fd6b03fcec.png)

**Comment by AMBudnik** [comment]
Hey @julniter 

I have replicated the issue and it seems to be the same at this one https://github.com/handsontable/formula-parser/issues/98
If we change variables to contain letters-only it works.
